# Generated by Django 3.1.4 on 2020-12-31 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='sexe',
            field=models.CharField(max_length=200),
        ),
    ]
