# Generated by Django 3.1.4 on 2020-12-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0002_auto_20201231_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='age',
            field=models.IntegerField(),
        ),
    ]
